---
# v 1.0.1
# Authored by Christian McKee - cmckee786@github.com
# Attempts to removes podman pihole pod and service account
#
# Tested on:
# Operating System: Rocky Linux 9.7 (Blue Onyx)
# CPE OS Name: cpe:/o:rocky:rocky:9::baseos
# Kernel: Linux 6.1.31-v8.1.el9.altarch
# Instruction Set: ARMv8-A
# Architecture: arm64
# SELinux: Disabled

- hosts: all
  become: true

  vars_files:
    - roles/pihole/defaults/main.yml

  tasks:
    - name: Disable linger for pihole service account
      ansible.builtin.command: "loginctl disable-linger {{ pihole_user }}"

    - name: Delete service account
      ansible.builtin.user:
        name: "{{ pihole_user }}"
        state: absent
        force: true

    - name: Remove necessary user home directories
      ansible.builtin.file:
        path: /home/{{ pihole_user }}/
        state: absent

    - name: Remove redirect rich rules
      ansible.posix.firewalld:
        rich_rule: "{{ item.rich_rule }}"
        zone: public
        immediate: true
        permanent: true
        state: absent
      loop:
        - rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080
        - rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
        - rich_rule: rule family=ipv4 forward-port port=53 protocol=tcp to-port=10053
        - rich_rule: rule family=ipv4 forward-port port=53 protocol=udp to-port=10053
